apl:
  name: 'Alexandria Library'
  building: 'Alexandria Library Local History/Special Collections'
  address1: '717 Queen Street'
  address2: 'Alexandria, Virginia 22314-2420'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/apl.jpg'
  contact: 'mailto:lhsc@alexandria.lib.va.us'
au:
  name: 'Averett University'
  building: 'Mary B. Blount Library Averett University'
  address1: '344 West Main St.'
  address2: 'Danville, VA 24541'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/au.jpg'
  contact: 'mailto:aclib@averett.edu'
bc:
  name: 'Bridgewater College'
  building: 'Special Collections Alexander Mack Memorial Library'
  address1: 'Bridgewater College'
  address2: '402 E. College St.'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/bc.jpg'
  contact: 'mailto:dharter@bridgewater.edu'
wm:
  name: 'College of William and Mary'
  building: 'Special Collections Earl Gregg Swem Library'
  address1: 'College of William and Mary'
  address2: 'Williamsburg, Virginia 23187-8794'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/wm.jpg'
  contact: 'mailto:spcoll@wm.edu'
cw:
  name: 'Colonial Williamsburg'
  building: 'John D. Rockefeller, Jr. Library Colonial Williamsburg Foundation'
  address1: 'P.O. Box 1776'
  address2: 'Williamsburg, Virginia 23187'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/cw.jpg'
  contact: 'mailto:speccoll@cwf.org'
fcpl:
  name: 'Fairfax County Public Library'
  building: 'Fairfax County Public Library City of Fairfax Regional Library'
  address1: 'Virginia Room'
  address2: '10360 North Street'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/FairfaxCoPL.tif'
  contact: 'mailto:va_room@fairfaxcounty.gov'
gmu:
  name: 'George Mason University'
  building: 'Special Collections & Archives Fenwick Library (2FL)'
  address1: 'George Mason University'
  address2: 'Fairfax, Virginia 22030-4444'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/gmu.jpg'
  contact: 'mailto:speccoll@gmu.edu'
gh:
  name: 'Gunston Hall'
  building: 'Gunston Hall Library & Archives'
  address1: '10709 Gunston Road'
  address2: 'Mason Neck, VA 22079'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/gunstonhall_logo.jpg'
  contact: 'mailto:mlee@gunstonhall.org'
hrl:
  name: 'Handley Regional Library'
  building: 'Stewart Bell Jr. Archives Room The Handley Regional Library'
  address1: 'Winchester-Frederick County Historical Society'
  address2: 'P.O. Box 58'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/handley.jpg'
  contact: 'mailto:archives@handleyregional.org' 
hu:
  name: 'Hollins University'
  building: 'Special Collections Wyndham Robertson Library'
  address1: 'P. O. Box 9000'
  address2: '7950 E. Campus Drive'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/Hollins%20Logo.bmp'
  contact: 'mailto:bharris@hollins.edu'
jmu:
  name: 'James Madison University'
  building: 'Special Collections Carrier Library'
  address1: 'James Madison University'
  address2: 'Harrisonburg, Virginia 22807'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/jmu.jpg'
  contact: 'mailto:library-special@jmu.edu'
lva:
  name: 'Library of Virginia'
  building: 'The Library of Virginia 800 East Broad Street'
  address1: 'Richmond, Virginia 23219-8000'
  address2: 'USA'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/lva.jpg'
  contact: 'mailto:archdesk@lva.virginia.gov (Archives)'
lu:
  name: 'Longwood University'
  building: 'Archives and Special Collections Greenwood Library'
  address1: 'Longwood University'
  address2: 'Redford and Race Streets'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/LongwoodLogo-320wide.gif'
  contact: 'mailto:specialcollections@longwood.edu'
mcc:
  name: 'Montgomery County Circuit Court'
  building: 'Montgomery County Circuit Court 55 East Main Street, Suite 1'
  address1: 'Christiansburg, VA 24073'
  address2: 'Phone: (540) 382-5760'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/MontgomeryCountySeal.jpg'
npl:
  name: 'Norfolk Public Library'
  building: 'Sargeant Memorial Collection Norfolk Public Library'
  address1: 'Slover Library'
  address2: '235 East Plume Street'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/npl-logo.jpg'
  contact: 'mailto:localhistory@norfolk.gov'
odu:
  name: 'Old Dominion University'
  building: 'Special Collections Perry Library'
  address1: 'Old Dominion University'
  address2: 'Norfolk, Virginia 23529-0256'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/odu.jpg'
  contact: 'mailto:libspecialcollections@odu.edu'
rc:
  name: 'Roanoke College'
  building: 'Roanoke College Archives 220 High St.'
  address1: 'Salem, VA 24153-3794'
  address2: 'USA'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/roanokecollege.gif'
  contact: 'mailto:lmiller@roanoke.edu'
rpl:
  name: 'Roanoke Public Libraries'
  building: 'Roanoke Public Libraries 706 South Jefferson Street'
  address1: 'Roanoke, Virginia 24016 USA'
  address2: 'Phone: (540) 853-2073'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/RPLlogo.jpg'
  contact: 'mailto:virginia‚Äùroom@gmail.com'
ru:
  name: 'Radford University'
  building: 'University Archives McConnell Library'
  address1: 'PO Box 6881'
  address2: '801 East Main Street'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/ru.jpg'
  contact: 'mailto:aspelbrin@radford.edu'
rmc:
  name: 'Randolph-Macon College'
  building: 'McGraw-Page Library Box 5005'
  address1: 'Randolph-Macon College'
  address2: 'Ashland, Virginia 23005-5505'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/rmc.jpg'
  contact: 'mailto:archives@rmc.edu'
tbl:
  name: 'Thomas Balch Library'
  building: 'Thomas Balch Library 208 West Market Street'
  address1: 'Leesburg, Virginia 20176'
  address2: 'USA'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/tbl.jpg'
  contact: 'mailto:balchlib@leesburgva.gov'
umw:
  name: 'University of Mary Washington'
  building: 'Special Collections Simpson Library'
  address1: '1801 College Avenue'
  address2: 'University of Mary Washington'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/umw.jpg'
  contact: 'mailto:refdesk@umw.edu'
ur:
  name: 'University of Richmond'
  building: 'Rare Books and Special Collections Boatwright Library'
  address1: 'University of Richmond'
  address2: '28 Westhampton Way'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/ur.jpg'
  contact: 'mailto:jgwin@richmond.edu'
uva-cnhi:
  name: 'University of Virginia, The Center for Nursing Historical Inquiry'
  building: 'University of Virginia School of Nursing'
  address1: 'The Center for Nursing Historical Inquiry'
  address2: '202 Jeanette Lancaster Way'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/ECBCNHI.jpg'
  contact: 'mailto:nurs-hxc@virginia.edu'
uva-hs:
  name: 'University of Virginia, Health Sciences Library'
  building: 'Historical Collections Claude Moore Health Sciences Library'
  address1: 'University of Virginia Health System'
  address2: '1350 Jefferson Park Avenue'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/uva-sc.jpg'
  contact: 'mailto:jre@virginia.edu'
uva-law:
  name: 'University of Virginia, Law Library'
  building: 'Special Collections Arthur J. Morris Law Library'
  address1: 'University of Virginia'
  address2: 'Charlottesville, Virginia 22903'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/uvalaw.jpg'
  contact: 'mailto:lawlibref@virginia.edu'
uva-music:
  name: 'University of Virginia, Music Library'
  building: ' '
  address1: ''
  address2: ''
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/uva-sc.jpg'
uva-sc:
  name: 'University of Virginia, Special Collections Dept.'
  building: 'Albert and Shirley Small Special Collections Library University of Virginia'
  address1: 'Charlottesville, Virginia 22904-4110'
  address2: 'USA'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/uva-sc.jpg'
vcu-cab:
  name: 'Virginia Commonwealth University, Cabell Library'
  building: 'Special Collections and Archives James Branch Cabell Library'
  address1: 'Box 842003'
  address2: 'Virginia Commonwealth University'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/vcu.jpg'
  contact: 'mailto:libjbcsca@vcu.edu'
vcu-tm:
  name: 'Virginia Commonwealth University, Tompkins-McCaw Library'
  building: 'Special Collections and Archives Tompkins-McCaw Library'
  address1: 'Box 980582'
  address2: 'Virginia Commonwealth University'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/vcu.jpg'
  contact: 'mailto:libtmlsca@vcu.edu'
vhs:
  name: 'Virginia Historical Society'
  building: 'Virginia Historical Society P.O. Box 7311'
  address1: 'Richmond, Virginia 23221-0311'
  address2: 'USA'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/vhs.jpg'
  contact: 'mailto:reference@vahistorical.org'
vmi:
  name: 'Virginia Military Institute'
  building: 'Virginia Military Institute Archives Preston Library'
  address1: 'Virginia Military Institute'
  address2: 'Lexington, Virginia 24450-0304'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/vmi.jpg'
  contact: 'mailto:archives@vmi.edu'
vmfa:
  name: 'Virginia Museum of Fine Arts'
  building: 'VMFA Archives Virginia Museum of Fine Arts'
  address1: 'Margaret R. and Robert M. Freeman Library'
  address2: '200 N. Boulevard'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/VMFA.jpg'
  contact: 'mailto:library@vmfa.museum'
vt:
  name: 'Virginia Polytechnic Institute and State University'
  building: 'Special Collections, University Libraries (0434) 560 Drillfield Drive'
  address1: 'Newman Library, Virginia Tech'
  address2: 'Blacksburg, Virginia 24061'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/vt.jpg'
  contact: 'mailto:specref@vt.edu'
vsll-scv:
  name: 'Virginia State Law Library, Supreme Court of Virginia'
  building: 'Virginia State Law Library Supreme Court of Virginia'
  address1: '100 North Ninth Street'
  address2: 'Richmond, Virginia 23219'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/scv.jpg'
  contact: 'mailto:LawLibrary@courts.state.va.us'
vsu:
  name: 'Virginia State University'
  building: 'Special Collections and Archives Johnston Memorial Library'
  address1: 'P.O. Box 9406'
  address2: 'Virginia State University'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/vsu.jpg'
  contact: 'mailto:ledwards@vsu.edu'
vuu:
  name: 'Virginia Union University'
  building: 'L. Douglas Wilder Library Virginia Union University'
  address1: '1500 North Lombardy Street'
  address2: 'Richmond, Virginia 23220'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/vuu.jpg'
  contact: 'mailto:sksteven@vuu.edu'
wl-law:
  name: 'Washington and Lee University, Law School'
  building: 'Lewis F. Powell, Jr. Archives Washington and Lee University'
  address1: 'School of Law'
  address2: 'Lexington, Virginia 24450-0303'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/wl-law.jpg'
  contact: 'mailto:powell@wlu.edu'
wl-ley:
  name: 'Washington and Lee University, Leyburn Library'
  building: 'Special Collections Lyeburn Library'
  address1: 'Washington and Lee University'
  address2: 'Lexington, Virginia 24450'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/wl.jpg'
  contact: 'mailto:stanleyv@wlu.edu'
wwplm:
  name: 'Woodrow Wilson Presidential Library & Museum'
  building: 'Woodrow Wilson Presidential Library & Museum 20 North Coalter Street,'
  address1: 'Staunton, Virginia  24401'
  address2: 'Phone: 540-885-0897'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/WWPLM.jpg'
  contact: ''
wcc:
  name: 'Wytheville Community College'
  building: 'Special Collections Kegley Library'
  address1: 'Wytheville Community College'
  address2: 'Wytheville, Virginia 24382-3308'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/wcc.jpg'
  contact: 'mailto:gmattis@wcc.vccs.edu'
wchs:
  name: 'Wythe County Historical Society'
  building: 'Wythe County Historical Society Research Library'
  address1: 'Heritage Preservation Center'
  address2: '115 W. Spiller Street'
  state: 'VA' 
  country: 'USA'
  thumbnail_url: 'http://ead.lib.virginia.edu/vivaead/logos/wythechs.png'
  contact: 'mailto:wch_library@wytheville.org'
